### ISSUE TITLE
Can you please update the execution time for my submission? or do we get one try per person

### ISSUE THREAD

**Issue by nizarbenalla** [geeksblabla/blanat#272]
I updated my code twice but the execution time wasn't changed, but other people's entries were added to the leaderboard.

**Comment by aboullaite** [comment]
We update the submission twice a day. When your submission was merged ? If it doesn't appear it means it is either wrong or timed out. Please read the readme for more info

**Comment by nizarbenalla** [comment]
it was merged yesterday evening
