### ISSUE TITLE
Don't merge my code

### ISSUE THREAD

**Issue by ibrataha8** [geeksblabla/blanat#283]
I sent my code and some were accepted and I was ignored

**Comment by aboullaite** [comment]
Please be mindful of the load we are getting and have some empathy for the team. We are having a full time job and reviewing dozens of PRs when we can. You do not have to accuse us :) we will review it when we can

**Comment by ibrataha8** [comment]
@aboullaite  I apologize, I appreciate your efforts that you provide for free

**Comment by aboullaite** [comment]
@viierr they simply weren't valid and the runner flagged them as wrong results

**Comment by viierr** [comment]
so wrong submissions are merged?

**Comment by aboullaite** [comment]
The evaluation only happen after the merge :)

**Comment by viierr** [comment]
ah understandable, thank you for your time
